[[sect_data_preparation]]
== Data Preparation

=== Sense Inventory Generation

==== Uby Lexicon Creation

* login to MySQL
----
$ mysql -u <user> -p <password>
----
* Create a database for the uby lexicon
----
mysql> CREATE DATABASE UBY_GN;
----

* Copy the GermaNet dump to import to the target directory of the *ubycreate* project

* Navigate to the target directory of the *ubycreate* project


* Run the already generated jar using the Germanet dump as the source argument and the name of the created UBY_GN database as the target argument
----
$  java -jar ubycreate-gpl-0.8.0-SNAPSHOT-standalone.jar --target mysql:root:pass@localhost:3306/UBY_GN --source germanet:GN_V70/GN_V70_XML
----
* The GermaNet data should be transformed now to a Uby lexicon in the UBY_GN database

==== Uby2Ubyline Conversion

* login to MySQL
----
$ mysql -u <user> -p <password>
----
* Create a database for the Ubyline
----
mysql> CREATE DATABASE UBYLINE;
----
* Copy the following lines to the "settings.properties" file  and replace the required parameters with your specific choice
----
database.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
database.driver=com.mysql.jdbc.Driver
database.url=jdbc:mysql://localhost:3306/UBYLINE
database.username=<user>
database.password=<your DB password>
uby.url=localhost/UBY_GN_9
lemmataList.location=<path to the lemma list>/list.txt
----

* The last copied line indicates to Ubyline the path to the list of lemmas to extract from Uby to Ubyline.
A conversion of the whole Uby lexicon is also possible but this requires a small change in the code.
The list should contain the lexical entries in Uby with its corresponding POS.
Using a different appellation for POS would cause errors during the conversion process. The list should have the following format:
----
Abbuchung.nounCommon
ablöschen.verb
abmalen.verb
abstürzen.verb
abwechselnd.adjective
----

* On your terminal, switch to the target directory of Ubyline project

* Run the Ubyline jar and provide the path to your Ubyline home dirctory to read the "settings.properties" file
----
  $  java -Dubyline.home="<path to ubyline home direectory>" -jar dkpro-uby-ubyline-0.2.4-SNAPSHOT-standalone.jar
----

=== Corpus Pre-Processing
In this documentation we use the lexical substitution data set described in Cholakov et al., 2013. The data set could downloaded from https://sites.google.com/site/germeval2015/data-sets.
For the sake of simplicity, we merged the "train.xml" and "test.xml" into one file "complete-dataset.xml".

* Copy the "complete-dataset.xml" in Ubyline home directory

* add to settings.properties the dataset parameters as in the following lines:
----
  dataset.path=<path to the dataset>
  dataset.name=complete-dataset.xml
----


* Download the binary distribution of the CWB from: http://cwb.sourceforge.net/download.php. The binaries contain files required for writing and reading data in cqp format

* Extract the content of the downloaded distribution to the Ubyline home directory

* add to settings.properties file the cqp parameters
----
  engine.cqp.home=<path to ubyline home directory>/cwb-3.0.0-linux-x86_64/bin
  engine.cqp.executable=<path to ubyline home directory>/cwb-3.0.0-linux-x86_64/bin/cqp
----

* On your terminal, switch to the target directory of Ubyline project

* Run the Ubyline jar and provide the path to your Ubyline home dirctory to read the "settings.properties" file
----
$ java -Dubyline.home="<path to ubyline home directory>" -cp dkpro-uby-ubyline-0.2.4-SNAPSHOT-standalone.jar de.tudarmstadt.ukp.ubyline.Writers.ToCQPFormatWriter
----
* A directory with the name *target* will be created. It contains a directory with the name *lexsubcorpus* which needs a restructuring

* Change the name of the directory in the the *LEXSUB* directory from “data” to “cqp”

* Change the location of the registry directory to be in the same level as *LEXSUB* and *binaryCases*

* Change the Home variable in the *lexsub* file in the *registry* directory to the path to the cqp directory as following:
----
# path to binary data files
HOME the path_to_the_cqp_directory
----
* The *lexsubcorpus* directory should have te following structure:
----
 	+-- _lexsubcorpus
 	|	+-- _binaryCases
 	|	+-- _LEXSUB
 	| 		+-- corpus.properties
 	|		+-- _cqp
 	|	+-- _registry
----

* Move the whole *lexsubcorpus* directory to Ubyline home directory

* Indicate the path to your lexsubcorpus directory in the settings.properties files for the variable corpus.service.path
----
corpus.service.path=<path to the lexsubcorpus directory>
----
