[[sect_installation]]
== Installation
Installation of Ubyline requires some prerequisites, a Uby lexicon and some configuration steps which are outlined below.

=== Prerequisites

* This guide assumes that you are using the following technologies:
 	* Ubuntu 14.04
	* MySQL 5.5
	* Java 7 or higher
	* Tomcat 7

It may also work on other versions with some modifications, but we do not test this.

=== Packaging

==== Ubycrete

To create a Uby lexicon, *ubycreate* tool should be used. In this guide, we use ubycreate to generate a Uby lexicon from a GermaNet XML dump

* Download the project from the GitHub repository: https://github.com/dkpro/dkpro-uby/tree/master/de.tudarmstadt.ukp.uby.ubycreate-gpl
* Navigate to the root directory of the project
* On your terminal, run the following command to generate the JAR file of the project
----
$ mvn package
----
* A file named "ubycreate-gpl-0.8.0-SNAPSHOT-standalone.jar" should be generated in the target directory of the project

==== Ubyline

Ubyline is a web application but has also embedded module for pre-processing data. To use all Ubyline functionalities, we need to generate a WAR and JAR files

* Download the project from the GitHub repository
* Navigate to the root directory of the project
* On your terminal, run the following command
----
$ mvn package
----
* Two file named "dkpro-uby-ubyline-0.2.4-SNAPSHOT-standalone.jar" and "dkpro-uby-ubyline-0.2.4-SNAPSHOT.war" should be generated in the target directory of the project

=== Configuration

A configuration file should be created for Ubyline to extract all the necessary parameters

* Create the file using any text editor and name it "settings.properties"

* Save the file under a directory of your choice. We will consider this as Ubyline home directory
